root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  full_bin = "env $(grep -v '^#' /Users/waynechen/_project/coverones/dev-stack/.env.local | grep -v '^$' | xargs) ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir  = ["tmp", "vendor", "testdata", "migrations"]
  delay        = 1000
  kill_delay   = "0s"
  rerun        = false
  rerun_delay  = 500

[log]
  time = false

[misc]
  clean_on_exit = true
